### PR TITLE
Forgot to change JPMS name to jakarta.mail

### PR DESCRIPTION
**Pull request by bshannon**

### CODE REVIEW

**Comment by m0mus** [comment]
Why are you changing module names now? I thought that we agreed not changing it before the Eclipse GlassFish release.

**Comment by bshannon** [comment]
The previous release of JavaMail defined a module name, even though it's not in the spec.
The sooner the java.* module name is eliminated, the better.  I'm not going to remove the
module name entirely and undo all the work I did for the previous release.

**Comment by m0mus** [comment]
It's fine to keep java.* module name. You don't need to undo all your previous work. **But you shouldn't change it to jakarta now**. If you do, all modules with javamail dependency must be updated. It's what I'm trying to avoid.

**Comment by bshannon** [comment]
I'm sure the number of applications using JPMS with JavaMail is very small, but the longer a version is out there with the "bad" module name, the more impact it will have when we change it.  I'm changing it now to reduce the impact of the change and avoid the need to create a compatibility module.

**Pull request merged**
