### PR TITLE
E 372 Add QUIT support on session rejection closes #372

### LINKED ISSUE #372: Add QUIT support on session rejection
Hi,

this is an old issue that was left over before Oracle -> ESF switch (my bad, I didn't sign old contributor agreement).

Add quit on session rejection as per https://tools.ietf.org/html/rfc5321#section-3.1. New property quitOnSessionReject defaults keeping old behaviour but can set to true to respect RFC.

### PR DESCRIPTION
**Pull request by diegosalvi**
Add quitOnSessionReject flag to conform to https://tools.ietf.org/html/rfc5321#section-3.1

Signed-off-by: Diego Salvi <lothruin.mirwen@gmail.com>

### CODE REVIEW

**Comment by diegosalvi** [comment]
Oh my bad, eclipse autoformat I presume. I'll revert and push back

Il giorno gio 7 feb 2019, 01:38 Bill Shannon <notifications@github.com> ha
scritto:

**Comment by bshannon** [comment]
@diegosalvi Can you fix this soon, please?

**Comment by diegosalvi** [comment]
Fixed :D

**Comment by diegosalvi** [comment]
Reverted some cast removed automatically by my IDE. Automatic tools sometimes generate more work :(

**Pull request merged**
